//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class actions_list
    {
        public int recid { get; set; }
        public string action_by { get; set; }
        public string action_item { get; set; }
        public string action_remarks { get; set; }
        public Nullable<System.DateTime> date_assigned { get; set; }
        public Nullable<System.DateTime> date_due { get; set; }
        public Nullable<System.DateTime> date_completed { get; set; }
        public Nullable<bool> status { get; set; }
        public string last_updated_by { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
