//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class appsetup
    {
        public int recid { get; set; }
        public string email_smtp_host { get; set; }
        public string moderator_firstname { get; set; }
        public string moderator_lastname { get; set; }
        public string default_email_originator { get; set; }
        public string default_email_recipient { get; set; }
        public string developer_firstname { get; set; }
        public string developer_lastname { get; set; }
        public string email_acknowledgement_text { get; set; }
        public string email_welcome_text { get; set; }
        public string marquee_text { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
