//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class articles_authors
    {
        public int recid { get; set; }
        public string author_firstname { get; set; }
        public string author_lastname { get; set; }
        public string organisation { get; set; }
        public string email_address { get; set; }
    }
}
