//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class auckland_local_boards
    {
        public int recid { get; set; }
        public string local_board { get; set; }
    }
}
