//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int recid { get; set; }
        public string doc_title { get; set; }
        public Nullable<int> doc_type_id { get; set; }
        public string doc_author { get; set; }
        public string doc_publisher { get; set; }
        public Nullable<System.DateTime> doc_date { get; set; }
        public string doc_number { get; set; }
        public string doc_remarks { get; set; }
        public string doc_path { get; set; }
        public Nullable<bool> status { get; set; }
        public string uploaded_by { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> date_deleted { get; set; }
    }
}
