//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiries_log
    {
        public int recid { get; set; }
        public Nullable<System.DateTime> datetimelog { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public string enquiry_source { get; set; }
        public string follow_up_by { get; set; }
        public Nullable<System.DateTime> follow_up_date { get; set; }
        public string follow_up_remarks { get; set; }
        public string meeting_by { get; set; }
        public Nullable<System.DateTime> meeting_date { get; set; }
        public string action_remarks { get; set; }
        public string last_updated_by { get; set; }
        public Nullable<System.DateTime> last_updated_date { get; set; }
        public Nullable<System.DateTime> completed_date { get; set; }
        public byte[] completed_by { get; set; }
        public string initial_response { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
