//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class good_neighbour_subscribers
    {
        public int recid { get; set; }
        public Nullable<int> member_id { get; set; }
        public string subscriber_name { get; set; }
        public Nullable<bool> pdf_subscription { get; set; }
        public Nullable<bool> print_subscription { get; set; }
        public Nullable<int> quantity { get; set; }
        public string subscriber_postal_address { get; set; }
        public string subscriber_email_address { get; set; }
    }
}
