//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_setup_schedule
    {
        public int recid { get; set; }
        public Nullable<System.DateTime> enquiry_received_date { get; set; }
        public string contact_firstname { get; set; }
        public string contact_lastname { get; set; }
        public string contact_address_unit_number { get; set; }
        public string contact_address_number { get; set; }
        public string contact_address_name { get; set; }
        public string contact_address_suburb { get; set; }
        public string contact_address_postcode { get; set; }
        public string contact_home_phone { get; set; }
        public string contact_cell_phone { get; set; }
        public string contact_email { get; set; }
        public Nullable<System.DateTime> meeting_date { get; set; }
        public string setup_by_username { get; set; }
        public Nullable<int> number_of_attendance { get; set; }
        public Nullable<bool> setup_status { get; set; }
        public string setup_remarks { get; set; }
        public Nullable<bool> follow_up_status { get; set; }
        public string follow_up_by_username { get; set; }
        public string follow_up_remarks { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
