//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public int recid { get; set; }
        public string group_name { get; set; }
        public string street_name { get; set; }
        public string suburb { get; set; }
        public Nullable<int> area_coordinator_id { get; set; }
        public string remarks { get; set; }
        public string setup_by { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
    }
}
