//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_members
    {
        public int recid { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<bool> street_contact_status { get; set; }
        public Nullable<bool> membership_status { get; set; }
        public Nullable<System.DateTime> last_updated { get; set; }
        public string last_updated_by { get; set; }
    }
}
