//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class members_backup
    {
        public int recid { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string gender { get; set; }
        public string physical_address_unit_number { get; set; }
        public string physical_address_number { get; set; }
        public string physical_address_name { get; set; }
        public string physical_address_suburb { get; set; }
        public string physical_address_postcode { get; set; }
        public string postal_address_number { get; set; }
        public string postal_address_box_lobby_location { get; set; }
        public string postal_address_suburb { get; set; }
        public string postal_address_postcode { get; set; }
        public string phone_home { get; set; }
        public string phone_work { get; set; }
        public string phone_cell { get; set; }
        public string email_address_default { get; set; }
        public string email_address_alternate { get; set; }
        public Nullable<System.DateTime> signup_date { get; set; }
        public string username { get; set; }
        public string ip_address { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> emergency_volunteering_status { get; set; }
        public Nullable<bool> mailing_list_status { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string occupation { get; set; }
        public string other_remarks { get; set; }
        public Nullable<System.DateTime> last_updated_date { get; set; }
        public string last_updated_by { get; set; }
    }
}
