//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NSAKLEntities : DbContext
    {
        public NSAKLEntities()
            : base("name=NSAKLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<user> users { get; set; }
        public DbSet<actions_list> actions_list { get; set; }
        public DbSet<appsetup> appsetups { get; set; }
        public DbSet<article> articles { get; set; }
        public DbSet<articles_authors> articles_authors { get; set; }
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_UsersInRoles> aspnet_UsersInRoles { get; set; }
        public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public DbSet<auckland_local_boards> auckland_local_boards { get; set; }
        public DbSet<committee> committees { get; set; }
        public DbSet<coordinator> coordinators { get; set; }
        public DbSet<deleted_group_members> deleted_group_members { get; set; }
        public DbSet<deleted_members> deleted_members { get; set; }
        public DbSet<doc_types> doc_types { get; set; }
        public DbSet<document> documents { get; set; }
        public DbSet<enquiries_log> enquiries_log { get; set; }
        public DbSet<good_neighbour_despatch_log> good_neighbour_despatch_log { get; set; }
        public DbSet<good_neighbour_subscribers> good_neighbour_subscribers { get; set; }
        public DbSet<group_members> group_members { get; set; }
        public DbSet<group_setup_schedule> group_setup_schedule { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<members_backup> members_backup { get; set; }
        public DbSet<nz_stats> nz_stats { get; set; }
        public DbSet<nzaddress_type> nzaddress_type { get; set; }
        public DbSet<nzaddress> nzaddresses { get; set; }
        public DbSet<nzregion> nzregions { get; set; }
        public DbSet<param> @params { get; set; }
        public DbSet<pobox_locations> pobox_locations { get; set; }
        public DbSet<police_districts> police_districts { get; set; }
        public DbSet<site_log> site_log { get; set; }
        public DbSet<style> styles { get; set; }
        public DbSet<suburbs_by_local_boards> suburbs_by_local_boards { get; set; }
        public DbSet<suspicious_vehicles> suspicious_vehicles { get; set; }
        public DbSet<test_details> test_details { get; set; }
        public DbSet<test1> test1 { get; set; }
        public DbSet<useful_contacts> useful_contacts { get; set; }
        public DbSet<vw_aspnet_Applications> vw_aspnet_Applications { get; set; }
        public DbSet<vw_aspnet_MembershipUsers> vw_aspnet_MembershipUsers { get; set; }
        public DbSet<vw_aspnet_Profiles> vw_aspnet_Profiles { get; set; }
        public DbSet<vw_aspnet_Roles> vw_aspnet_Roles { get; set; }
        public DbSet<vw_aspnet_Users> vw_aspnet_Users { get; set; }
        public DbSet<vw_aspnet_UsersInRoles> vw_aspnet_UsersInRoles { get; set; }
        public DbSet<vw_aspnet_WebPartState_Paths> vw_aspnet_WebPartState_Paths { get; set; }
        public DbSet<vw_aspnet_WebPartState_Shared> vw_aspnet_WebPartState_Shared { get; set; }
        public DbSet<vw_aspnet_WebPartState_User> vw_aspnet_WebPartState_User { get; set; }
    }
}
