//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class police_districts
    {
        public int recid { get; set; }
        public string police_district { get; set; }
        public string community_constable { get; set; }
        public string office_address { get; set; }
        public string email_address { get; set; }
        public string phone { get; set; }
        public Nullable<int> nz_region_id { get; set; }
        public string news_page_url { get; set; }
        public Nullable<bool> status { get; set; }
        public string updated_by { get; set; }
    }
}
