//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_log
    {
        public int recid { get; set; }
        public Nullable<System.DateTime> first_accessed { get; set; }
        public string ip_address { get; set; }
        public Nullable<System.DateTime> last_accessed { get; set; }
        public Nullable<long> number_of_visits { get; set; }
        public string remarks { get; set; }
    }
}
