//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class suspicious_vehicles
    {
        public int recid { get; set; }
        public Nullable<System.DateTime> logdatetime { get; set; }
        public string registration_number { get; set; }
        public string vehicle_type { get; set; }
        public string vehicle_colour { get; set; }
        public string vehicle_model { get; set; }
        public string location { get; set; }
        public Nullable<short> passengers { get; set; }
        public string activity { get; set; }
        public string remarks { get; set; }
    }
}
