//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_details
    {
        public int recid { get; set; }
        public Nullable<int> test_id { get; set; }
        public byte[] testaasdas { get; set; }
    }
}
