//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSALK
{
    using System;
    using System.Collections.Generic;
    
    public partial class useful_contacts
    {
        public int recid { get; set; }
        public string service_name { get; set; }
        public string service_phone_1 { get; set; }
        public string service_phone_2 { get; set; }
        public string service_email_1 { get; set; }
        public string service_email_2 { get; set; }
        public string service_url_1 { get; set; }
        public string service_url_2 { get; set; }
    }
}
