// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>NSALK.Models.GetContacts</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>ASCII</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace NSALK.Models.GetContacts
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using NSALK.Areas.HelpPage.ModelDescriptions;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    [ModelName("NSALK.Models.GetContacts.SystemDataMessage")]
    public partial class SystemDataMessage
    {

        private List<SystemDataMessageContacts> itemsField;

        public SystemDataMessage()
        {
            this.itemsField = new List<SystemDataMessageContacts>();
        }

        [System.Xml.Serialization.XmlElementAttribute("Contacts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<SystemDataMessageContacts> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [ModelName("NSALK.Models.GetContacts.SystemDataMessageContacts")]
    public partial class SystemDataMessageContacts
    {

        private List<SystemDataMessageContact> contactField;

        public SystemDataMessageContacts()
        {
            this.contactField = new List<SystemDataMessageContact>();
        }



        [System.Xml.Serialization.XmlElementAttribute("Contact", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<SystemDataMessageContact> Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class SystemDataMessageContact
    {

        private int recidField;
        private string firstnameField;
        private string middlenameField;
        private string lastnameField;
        private string genderField;
        private string physical_address_unit_numberField;
        private string physical_address_numberField;
        private string physical_address_nameField;
        private string physical_address_suburbField;
        private string physical_address_postcodeField;
        private string postal_address_numberField;
        private string postal_address_box_lobby_locationField;
        private string postal_address_suburbField;
        private string postal_address_postcodeField;
        private string phone_homeField;
        private string phone_workField;
        private string phone_cellField;
        private string email_address_defaultField;
        private string email_address_alternateField;
        private string usernameField;
        private string ip_addressField;
        private string remarksField;
        private string occupationField;
        private string other_remarksField;
        private string last_updated_byField;
        private string signup_dateField;
        private Nullable<bool> emergency_volunteering_statusField;
        private Nullable<bool> mailing_list_statusField;
        private Nullable<bool> statusField;
        private string birth_dateField;
        private string last_updated_dateField;
        private int selectedGroupField;
        private int selectedCoordinatorField;
        
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SelectedCoordinator { get { return this.selectedCoordinatorField; } set { this.selectedCoordinatorField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SelectedGroup { get { return this.selectedGroupField; } set { this.selectedGroupField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Recid { get { return this.recidField; } set { this.recidField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Firstname { get { return this.firstnameField; } set { this.firstnameField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Middlename { get { return this.middlenameField; } set { this.middlenameField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lastname { get { return this.lastnameField; } set { this.lastnameField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gender { get { return this.genderField; } set { this.genderField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Physical_address_unit_number { get { return this.physical_address_unit_numberField; } set { this.physical_address_unit_numberField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Physical_address_number { get { return this.physical_address_numberField; } set { this.physical_address_numberField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Physical_address_name { get { return this.physical_address_nameField; } set { this.physical_address_nameField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Physical_address_suburb { get { return this.physical_address_suburbField; } set { this.physical_address_suburbField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Physical_address_postcode { get { return this.physical_address_postcodeField; } set { this.physical_address_postcodeField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postal_address_number { get { return this.postal_address_numberField; } set { this.postal_address_numberField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postal_address_box_lobby_location { get { return this.postal_address_box_lobby_locationField; } set { this.postal_address_box_lobby_locationField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postal_address_suburb { get { return this.postal_address_suburbField; } set { this.postal_address_suburbField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Postal_address_postcode { get { return this.postal_address_postcodeField; } set { this.postal_address_postcodeField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone_home { get { return this.phone_homeField; } set { this.phone_homeField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone_work { get { return this.phone_workField; } set { this.phone_workField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone_cell { get { return this.phone_cellField; } set { this.phone_cellField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email_address_default { get { return this.email_address_defaultField; } set { this.email_address_defaultField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email_address_alternate { get { return this.email_address_alternateField; } set { this.email_address_alternateField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username { get { return this.usernameField; } set { this.usernameField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ip_address { get { return this.ip_addressField; } set { this.ip_addressField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Remarks { get { return this.remarksField; } set { this.remarksField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Occupation { get { return this.occupationField; } set { this.occupationField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Other_remarks { get { return this.other_remarksField; } set { this.other_remarksField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Last_updated_by { get { return this.last_updated_byField; } set { this.last_updated_byField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Signup_date { get { return this.signup_dateField; } set { this.signup_dateField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nullable<bool> Emergency_volunteering_status { get { return this.emergency_volunteering_statusField; } set { this.emergency_volunteering_statusField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nullable<bool> Mailing_list_status { get { return this.mailing_list_statusField; } set { this.mailing_list_statusField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Nullable<bool> Status { get { return this.statusField; } set { this.statusField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Birth_date { get { return this.birth_dateField; } set { this.birth_dateField = value; } }
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Last_updated_date { get { return this.last_updated_dateField; } set { this.last_updated_dateField = value; } }


    }
}